// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "is_claimed", Type: field.TypeBool, Default: false},
		{Name: "expired_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "phone_number", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "first_name", Type: field.TypeString, Size: 255},
		{Name: "last_name", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"CUSTOMER", "ADMIN"}},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"ACTIVE", "DEACTIVE"}},
		{Name: "password_salt", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RefreshTokensTable,
		UsersTable,
	}
)

func init() {
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
}
