// Code generated by ent, DO NOT EDIT.

package ent

import (
	"automatic-doodle/ent/job"
	"automatic-doodle/ent/predicate"
	"automatic-doodle/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (ju *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetStartDate sets the "start_date" field.
func (ju *JobUpdate) SetStartDate(t time.Time) *JobUpdate {
	ju.mutation.SetStartDate(t)
	return ju
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (ju *JobUpdate) SetNillableStartDate(t *time.Time) *JobUpdate {
	if t != nil {
		ju.SetStartDate(*t)
	}
	return ju
}

// ClearStartDate clears the value of the "start_date" field.
func (ju *JobUpdate) ClearStartDate() *JobUpdate {
	ju.mutation.ClearStartDate()
	return ju
}

// SetEndDate sets the "end_date" field.
func (ju *JobUpdate) SetEndDate(t time.Time) *JobUpdate {
	ju.mutation.SetEndDate(t)
	return ju
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (ju *JobUpdate) SetNillableEndDate(t *time.Time) *JobUpdate {
	if t != nil {
		ju.SetEndDate(*t)
	}
	return ju
}

// ClearEndDate clears the value of the "end_date" field.
func (ju *JobUpdate) ClearEndDate() *JobUpdate {
	ju.mutation.ClearEndDate()
	return ju
}

// SetFee sets the "fee" field.
func (ju *JobUpdate) SetFee(i int) *JobUpdate {
	ju.mutation.ResetFee()
	ju.mutation.SetFee(i)
	return ju
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (ju *JobUpdate) SetNillableFee(i *int) *JobUpdate {
	if i != nil {
		ju.SetFee(*i)
	}
	return ju
}

// AddFee adds i to the "fee" field.
func (ju *JobUpdate) AddFee(i int) *JobUpdate {
	ju.mutation.AddFee(i)
	return ju
}

// SetJobType sets the "job_type" field.
func (ju *JobUpdate) SetJobType(s string) *JobUpdate {
	ju.mutation.SetJobType(s)
	return ju
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (ju *JobUpdate) SetNillableJobType(s *string) *JobUpdate {
	if s != nil {
		ju.SetJobType(*s)
	}
	return ju
}

// SetDescription sets the "description" field.
func (ju *JobUpdate) SetDescription(s string) *JobUpdate {
	ju.mutation.SetDescription(s)
	return ju
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ju *JobUpdate) SetNillableDescription(s *string) *JobUpdate {
	if s != nil {
		ju.SetDescription(*s)
	}
	return ju
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ju *JobUpdate) SetUserID(id uuid.UUID) *JobUpdate {
	ju.mutation.SetUserID(id)
	return ju
}

// SetUser sets the "user" edge to the User entity.
func (ju *JobUpdate) SetUser(u *User) *JobUpdate {
	return ju.SetUserID(u.ID)
}

// Mutation returns the JobMutation object of the builder.
func (ju *JobUpdate) Mutation() *JobMutation {
	return ju.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ju *JobUpdate) ClearUser() *JobUpdate {
	ju.mutation.ClearUser()
	return ju
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JobUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JobUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ju *JobUpdate) check() error {
	if v, ok := ju.mutation.Fee(); ok {
		if err := job.FeeValidator(v); err != nil {
			return &ValidationError{Name: "fee", err: fmt.Errorf(`ent: validator failed for field "Job.fee": %w`, err)}
		}
	}
	if v, ok := ju.mutation.JobType(); ok {
		if err := job.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "Job.job_type": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Description(); ok {
		if err := job.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Job.description": %w`, err)}
		}
	}
	if ju.mutation.UserCleared() && len(ju.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Job.user"`)
	}
	return nil
}

func (ju *JobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ju.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.StartDate(); ok {
		_spec.SetField(job.FieldStartDate, field.TypeTime, value)
	}
	if ju.mutation.StartDateCleared() {
		_spec.ClearField(job.FieldStartDate, field.TypeTime)
	}
	if value, ok := ju.mutation.EndDate(); ok {
		_spec.SetField(job.FieldEndDate, field.TypeTime, value)
	}
	if ju.mutation.EndDateCleared() {
		_spec.ClearField(job.FieldEndDate, field.TypeTime)
	}
	if value, ok := ju.mutation.Fee(); ok {
		_spec.SetField(job.FieldFee, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedFee(); ok {
		_spec.AddField(job.FieldFee, field.TypeInt, value)
	}
	if value, ok := ju.mutation.JobType(); ok {
		_spec.SetField(job.FieldJobType, field.TypeString, value)
	}
	if value, ok := ju.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
	}
	if ju.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ju.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetStartDate sets the "start_date" field.
func (juo *JobUpdateOne) SetStartDate(t time.Time) *JobUpdateOne {
	juo.mutation.SetStartDate(t)
	return juo
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableStartDate(t *time.Time) *JobUpdateOne {
	if t != nil {
		juo.SetStartDate(*t)
	}
	return juo
}

// ClearStartDate clears the value of the "start_date" field.
func (juo *JobUpdateOne) ClearStartDate() *JobUpdateOne {
	juo.mutation.ClearStartDate()
	return juo
}

// SetEndDate sets the "end_date" field.
func (juo *JobUpdateOne) SetEndDate(t time.Time) *JobUpdateOne {
	juo.mutation.SetEndDate(t)
	return juo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableEndDate(t *time.Time) *JobUpdateOne {
	if t != nil {
		juo.SetEndDate(*t)
	}
	return juo
}

// ClearEndDate clears the value of the "end_date" field.
func (juo *JobUpdateOne) ClearEndDate() *JobUpdateOne {
	juo.mutation.ClearEndDate()
	return juo
}

// SetFee sets the "fee" field.
func (juo *JobUpdateOne) SetFee(i int) *JobUpdateOne {
	juo.mutation.ResetFee()
	juo.mutation.SetFee(i)
	return juo
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableFee(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetFee(*i)
	}
	return juo
}

// AddFee adds i to the "fee" field.
func (juo *JobUpdateOne) AddFee(i int) *JobUpdateOne {
	juo.mutation.AddFee(i)
	return juo
}

// SetJobType sets the "job_type" field.
func (juo *JobUpdateOne) SetJobType(s string) *JobUpdateOne {
	juo.mutation.SetJobType(s)
	return juo
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableJobType(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetJobType(*s)
	}
	return juo
}

// SetDescription sets the "description" field.
func (juo *JobUpdateOne) SetDescription(s string) *JobUpdateOne {
	juo.mutation.SetDescription(s)
	return juo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableDescription(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetDescription(*s)
	}
	return juo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (juo *JobUpdateOne) SetUserID(id uuid.UUID) *JobUpdateOne {
	juo.mutation.SetUserID(id)
	return juo
}

// SetUser sets the "user" edge to the User entity.
func (juo *JobUpdateOne) SetUser(u *User) *JobUpdateOne {
	return juo.SetUserID(u.ID)
}

// Mutation returns the JobMutation object of the builder.
func (juo *JobUpdateOne) Mutation() *JobMutation {
	return juo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (juo *JobUpdateOne) ClearUser() *JobUpdateOne {
	juo.mutation.ClearUser()
	return juo
}

// Where appends a list predicates to the JobUpdate builder.
func (juo *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Job entity.
func (juo *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JobUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (juo *JobUpdateOne) check() error {
	if v, ok := juo.mutation.Fee(); ok {
		if err := job.FeeValidator(v); err != nil {
			return &ValidationError{Name: "fee", err: fmt.Errorf(`ent: validator failed for field "Job.fee": %w`, err)}
		}
	}
	if v, ok := juo.mutation.JobType(); ok {
		if err := job.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "Job.job_type": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Description(); ok {
		if err := job.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Job.description": %w`, err)}
		}
	}
	if juo.mutation.UserCleared() && len(juo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Job.user"`)
	}
	return nil
}

func (juo *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := juo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.StartDate(); ok {
		_spec.SetField(job.FieldStartDate, field.TypeTime, value)
	}
	if juo.mutation.StartDateCleared() {
		_spec.ClearField(job.FieldStartDate, field.TypeTime)
	}
	if value, ok := juo.mutation.EndDate(); ok {
		_spec.SetField(job.FieldEndDate, field.TypeTime, value)
	}
	if juo.mutation.EndDateCleared() {
		_spec.ClearField(job.FieldEndDate, field.TypeTime)
	}
	if value, ok := juo.mutation.Fee(); ok {
		_spec.SetField(job.FieldFee, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedFee(); ok {
		_spec.AddField(job.FieldFee, field.TypeInt, value)
	}
	if value, ok := juo.mutation.JobType(); ok {
		_spec.SetField(job.FieldJobType, field.TypeString, value)
	}
	if value, ok := juo.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
	}
	if juo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := juo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Job{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
