// Code generated by ent, DO NOT EDIT.

package ent

import (
	"automatic-doodle/ent/jobapplication"
	"automatic-doodle/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobApplicationDelete is the builder for deleting a JobApplication entity.
type JobApplicationDelete struct {
	config
	hooks    []Hook
	mutation *JobApplicationMutation
}

// Where appends a list predicates to the JobApplicationDelete builder.
func (jad *JobApplicationDelete) Where(ps ...predicate.JobApplication) *JobApplicationDelete {
	jad.mutation.Where(ps...)
	return jad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jad *JobApplicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jad.sqlExec, jad.mutation, jad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jad *JobApplicationDelete) ExecX(ctx context.Context) int {
	n, err := jad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jad *JobApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jobapplication.Table, sqlgraph.NewFieldSpec(jobapplication.FieldID, field.TypeUUID))
	if ps := jad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jad.mutation.done = true
	return affected, err
}

// JobApplicationDeleteOne is the builder for deleting a single JobApplication entity.
type JobApplicationDeleteOne struct {
	jad *JobApplicationDelete
}

// Where appends a list predicates to the JobApplicationDelete builder.
func (jado *JobApplicationDeleteOne) Where(ps ...predicate.JobApplication) *JobApplicationDeleteOne {
	jado.jad.mutation.Where(ps...)
	return jado
}

// Exec executes the deletion query.
func (jado *JobApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := jado.jad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jobapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jado *JobApplicationDeleteOne) ExecX(ctx context.Context) {
	if err := jado.Exec(ctx); err != nil {
		panic(err)
	}
}
