// Code generated by ent, DO NOT EDIT.

package ent

import (
	"automatic-doodle/ent/job"
	"automatic-doodle/ent/jobapplication"
	"automatic-doodle/ent/predicate"
	"automatic-doodle/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// JobApplicationQuery is the builder for querying JobApplication entities.
type JobApplicationQuery struct {
	config
	ctx        *QueryContext
	order      []jobapplication.OrderOption
	inters     []Interceptor
	predicates []predicate.JobApplication
	withUser   *UserQuery
	withJob    *JobQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobApplicationQuery builder.
func (jaq *JobApplicationQuery) Where(ps ...predicate.JobApplication) *JobApplicationQuery {
	jaq.predicates = append(jaq.predicates, ps...)
	return jaq
}

// Limit the number of records to be returned by this query.
func (jaq *JobApplicationQuery) Limit(limit int) *JobApplicationQuery {
	jaq.ctx.Limit = &limit
	return jaq
}

// Offset to start from.
func (jaq *JobApplicationQuery) Offset(offset int) *JobApplicationQuery {
	jaq.ctx.Offset = &offset
	return jaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jaq *JobApplicationQuery) Unique(unique bool) *JobApplicationQuery {
	jaq.ctx.Unique = &unique
	return jaq
}

// Order specifies how the records should be ordered.
func (jaq *JobApplicationQuery) Order(o ...jobapplication.OrderOption) *JobApplicationQuery {
	jaq.order = append(jaq.order, o...)
	return jaq
}

// QueryUser chains the current query on the "user" edge.
func (jaq *JobApplicationQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: jaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobapplication.Table, jobapplication.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobapplication.UserTable, jobapplication.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(jaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJob chains the current query on the "job" edge.
func (jaq *JobApplicationQuery) QueryJob() *JobQuery {
	query := (&JobClient{config: jaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobapplication.Table, jobapplication.FieldID, selector),
			sqlgraph.To(job.Table, job.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobapplication.JobTable, jobapplication.JobColumn),
		)
		fromU = sqlgraph.SetNeighbors(jaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JobApplication entity from the query.
// Returns a *NotFoundError when no JobApplication was found.
func (jaq *JobApplicationQuery) First(ctx context.Context) (*JobApplication, error) {
	nodes, err := jaq.Limit(1).All(setContextOp(ctx, jaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobapplication.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jaq *JobApplicationQuery) FirstX(ctx context.Context) *JobApplication {
	node, err := jaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobApplication ID from the query.
// Returns a *NotFoundError when no JobApplication ID was found.
func (jaq *JobApplicationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = jaq.Limit(1).IDs(setContextOp(ctx, jaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobapplication.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jaq *JobApplicationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := jaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobApplication entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobApplication entity is found.
// Returns a *NotFoundError when no JobApplication entities are found.
func (jaq *JobApplicationQuery) Only(ctx context.Context) (*JobApplication, error) {
	nodes, err := jaq.Limit(2).All(setContextOp(ctx, jaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobapplication.Label}
	default:
		return nil, &NotSingularError{jobapplication.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jaq *JobApplicationQuery) OnlyX(ctx context.Context) *JobApplication {
	node, err := jaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobApplication ID in the query.
// Returns a *NotSingularError when more than one JobApplication ID is found.
// Returns a *NotFoundError when no entities are found.
func (jaq *JobApplicationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = jaq.Limit(2).IDs(setContextOp(ctx, jaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobapplication.Label}
	default:
		err = &NotSingularError{jobapplication.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jaq *JobApplicationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := jaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobApplications.
func (jaq *JobApplicationQuery) All(ctx context.Context) ([]*JobApplication, error) {
	ctx = setContextOp(ctx, jaq.ctx, ent.OpQueryAll)
	if err := jaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JobApplication, *JobApplicationQuery]()
	return withInterceptors[[]*JobApplication](ctx, jaq, qr, jaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jaq *JobApplicationQuery) AllX(ctx context.Context) []*JobApplication {
	nodes, err := jaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobApplication IDs.
func (jaq *JobApplicationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if jaq.ctx.Unique == nil && jaq.path != nil {
		jaq.Unique(true)
	}
	ctx = setContextOp(ctx, jaq.ctx, ent.OpQueryIDs)
	if err = jaq.Select(jobapplication.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jaq *JobApplicationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := jaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jaq *JobApplicationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jaq.ctx, ent.OpQueryCount)
	if err := jaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jaq, querierCount[*JobApplicationQuery](), jaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jaq *JobApplicationQuery) CountX(ctx context.Context) int {
	count, err := jaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jaq *JobApplicationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jaq.ctx, ent.OpQueryExist)
	switch _, err := jaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jaq *JobApplicationQuery) ExistX(ctx context.Context) bool {
	exist, err := jaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobApplicationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jaq *JobApplicationQuery) Clone() *JobApplicationQuery {
	if jaq == nil {
		return nil
	}
	return &JobApplicationQuery{
		config:     jaq.config,
		ctx:        jaq.ctx.Clone(),
		order:      append([]jobapplication.OrderOption{}, jaq.order...),
		inters:     append([]Interceptor{}, jaq.inters...),
		predicates: append([]predicate.JobApplication{}, jaq.predicates...),
		withUser:   jaq.withUser.Clone(),
		withJob:    jaq.withJob.Clone(),
		// clone intermediate query.
		sql:  jaq.sql.Clone(),
		path: jaq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (jaq *JobApplicationQuery) WithUser(opts ...func(*UserQuery)) *JobApplicationQuery {
	query := (&UserClient{config: jaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	jaq.withUser = query
	return jaq
}

// WithJob tells the query-builder to eager-load the nodes that are connected to
// the "job" edge. The optional arguments are used to configure the query builder of the edge.
func (jaq *JobApplicationQuery) WithJob(opts ...func(*JobQuery)) *JobApplicationQuery {
	query := (&JobClient{config: jaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	jaq.withJob = query
	return jaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobApplication.Query().
//		GroupBy(jobapplication.FieldDescription).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jaq *JobApplicationQuery) GroupBy(field string, fields ...string) *JobApplicationGroupBy {
	jaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JobApplicationGroupBy{build: jaq}
	grbuild.flds = &jaq.ctx.Fields
	grbuild.label = jobapplication.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description,omitempty"`
//	}
//
//	client.JobApplication.Query().
//		Select(jobapplication.FieldDescription).
//		Scan(ctx, &v)
func (jaq *JobApplicationQuery) Select(fields ...string) *JobApplicationSelect {
	jaq.ctx.Fields = append(jaq.ctx.Fields, fields...)
	sbuild := &JobApplicationSelect{JobApplicationQuery: jaq}
	sbuild.label = jobapplication.Label
	sbuild.flds, sbuild.scan = &jaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JobApplicationSelect configured with the given aggregations.
func (jaq *JobApplicationQuery) Aggregate(fns ...AggregateFunc) *JobApplicationSelect {
	return jaq.Select().Aggregate(fns...)
}

func (jaq *JobApplicationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jaq); err != nil {
				return err
			}
		}
	}
	for _, f := range jaq.ctx.Fields {
		if !jobapplication.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jaq.path != nil {
		prev, err := jaq.path(ctx)
		if err != nil {
			return err
		}
		jaq.sql = prev
	}
	return nil
}

func (jaq *JobApplicationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JobApplication, error) {
	var (
		nodes       = []*JobApplication{}
		_spec       = jaq.querySpec()
		loadedTypes = [2]bool{
			jaq.withUser != nil,
			jaq.withJob != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JobApplication).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JobApplication{config: jaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := jaq.withUser; query != nil {
		if err := jaq.loadUser(ctx, query, nodes, nil,
			func(n *JobApplication, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := jaq.withJob; query != nil {
		if err := jaq.loadJob(ctx, query, nodes, nil,
			func(n *JobApplication, e *Job) { n.Edges.Job = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (jaq *JobApplicationQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*JobApplication, init func(*JobApplication), assign func(*JobApplication, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*JobApplication)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (jaq *JobApplicationQuery) loadJob(ctx context.Context, query *JobQuery, nodes []*JobApplication, init func(*JobApplication), assign func(*JobApplication, *Job)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*JobApplication)
	for i := range nodes {
		fk := nodes[i].JobID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(job.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "job_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (jaq *JobApplicationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jaq.querySpec()
	_spec.Node.Columns = jaq.ctx.Fields
	if len(jaq.ctx.Fields) > 0 {
		_spec.Unique = jaq.ctx.Unique != nil && *jaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jaq.driver, _spec)
}

func (jaq *JobApplicationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jobapplication.Table, jobapplication.Columns, sqlgraph.NewFieldSpec(jobapplication.FieldID, field.TypeUUID))
	_spec.From = jaq.sql
	if unique := jaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jaq.path != nil {
		_spec.Unique = true
	}
	if fields := jaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobapplication.FieldID)
		for i := range fields {
			if fields[i] != jobapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if jaq.withUser != nil {
			_spec.Node.AddColumnOnce(jobapplication.FieldUserID)
		}
		if jaq.withJob != nil {
			_spec.Node.AddColumnOnce(jobapplication.FieldJobID)
		}
	}
	if ps := jaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jaq *JobApplicationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jaq.driver.Dialect())
	t1 := builder.Table(jobapplication.Table)
	columns := jaq.ctx.Fields
	if len(columns) == 0 {
		columns = jobapplication.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jaq.sql != nil {
		selector = jaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jaq.ctx.Unique != nil && *jaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jaq.predicates {
		p(selector)
	}
	for _, p := range jaq.order {
		p(selector)
	}
	if offset := jaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobApplicationGroupBy is the group-by builder for JobApplication entities.
type JobApplicationGroupBy struct {
	selector
	build *JobApplicationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jagb *JobApplicationGroupBy) Aggregate(fns ...AggregateFunc) *JobApplicationGroupBy {
	jagb.fns = append(jagb.fns, fns...)
	return jagb
}

// Scan applies the selector query and scans the result into the given value.
func (jagb *JobApplicationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jagb.build.ctx, ent.OpQueryGroupBy)
	if err := jagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobApplicationQuery, *JobApplicationGroupBy](ctx, jagb.build, jagb, jagb.build.inters, v)
}

func (jagb *JobApplicationGroupBy) sqlScan(ctx context.Context, root *JobApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jagb.fns))
	for _, fn := range jagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jagb.flds)+len(jagb.fns))
		for _, f := range *jagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JobApplicationSelect is the builder for selecting fields of JobApplication entities.
type JobApplicationSelect struct {
	*JobApplicationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jas *JobApplicationSelect) Aggregate(fns ...AggregateFunc) *JobApplicationSelect {
	jas.fns = append(jas.fns, fns...)
	return jas
}

// Scan applies the selector query and scans the result into the given value.
func (jas *JobApplicationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jas.ctx, ent.OpQuerySelect)
	if err := jas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobApplicationQuery, *JobApplicationSelect](ctx, jas.JobApplicationQuery, jas, jas.inters, v)
}

func (jas *JobApplicationSelect) sqlScan(ctx context.Context, root *JobApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jas.fns))
	for _, fn := range jas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
