// Code generated by ent, DO NOT EDIT.

package ent

import (
	"automatic-doodle/ent/predicate"
	"automatic-doodle/ent/refreshtoken"
	"automatic-doodle/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RefreshTokenUpdate is the builder for updating RefreshToken entities.
type RefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtu *RefreshTokenUpdate) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdate {
	rtu.mutation.Where(ps...)
	return rtu
}

// SetToken sets the "token" field.
func (rtu *RefreshTokenUpdate) SetToken(s string) *RefreshTokenUpdate {
	rtu.mutation.SetToken(s)
	return rtu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableToken(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetToken(*s)
	}
	return rtu
}

// SetIsClaimed sets the "is_claimed" field.
func (rtu *RefreshTokenUpdate) SetIsClaimed(b bool) *RefreshTokenUpdate {
	rtu.mutation.SetIsClaimed(b)
	return rtu
}

// SetNillableIsClaimed sets the "is_claimed" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableIsClaimed(b *bool) *RefreshTokenUpdate {
	if b != nil {
		rtu.SetIsClaimed(*b)
	}
	return rtu
}

// SetUserID sets the "user_id" field.
func (rtu *RefreshTokenUpdate) SetUserID(u uuid.UUID) *RefreshTokenUpdate {
	rtu.mutation.SetUserID(u)
	return rtu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableUserID(u *uuid.UUID) *RefreshTokenUpdate {
	if u != nil {
		rtu.SetUserID(*u)
	}
	return rtu
}

// SetUpdatedAt sets the "updated_at" field.
func (rtu *RefreshTokenUpdate) SetUpdatedAt(t time.Time) *RefreshTokenUpdate {
	rtu.mutation.SetUpdatedAt(t)
	return rtu
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (rtu *RefreshTokenUpdate) SetUsersID(id uuid.UUID) *RefreshTokenUpdate {
	rtu.mutation.SetUsersID(id)
	return rtu
}

// SetUsers sets the "users" edge to the User entity.
func (rtu *RefreshTokenUpdate) SetUsers(u *User) *RefreshTokenUpdate {
	return rtu.SetUsersID(u.ID)
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtu *RefreshTokenUpdate) Mutation() *RefreshTokenMutation {
	return rtu.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (rtu *RefreshTokenUpdate) ClearUsers() *RefreshTokenUpdate {
	rtu.mutation.ClearUsers()
	return rtu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rtu *RefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	rtu.defaults()
	return withHooks(ctx, rtu.sqlSave, rtu.mutation, rtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := rtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rtu *RefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := rtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := rtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rtu *RefreshTokenUpdate) defaults() {
	if _, ok := rtu.mutation.UpdatedAt(); !ok {
		v := refreshtoken.UpdateDefaultUpdatedAt()
		rtu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtu *RefreshTokenUpdate) check() error {
	if v, ok := rtu.mutation.Token(); ok {
		if err := refreshtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.token": %w`, err)}
		}
	}
	if rtu.mutation.UsersCleared() && len(rtu.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RefreshToken.users"`)
	}
	return nil
}

func (rtu *RefreshTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	if ps := rtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtu.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := rtu.mutation.IsClaimed(); ok {
		_spec.SetField(refreshtoken.FieldIsClaimed, field.TypeBool, value)
	}
	if value, ok := rtu.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if rtu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtoken.UsersTable,
			Columns: []string{refreshtoken.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtoken.UsersTable,
			Columns: []string{refreshtoken.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rtu.mutation.done = true
	return n, nil
}

// RefreshTokenUpdateOne is the builder for updating a single RefreshToken entity.
type RefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// SetToken sets the "token" field.
func (rtuo *RefreshTokenUpdateOne) SetToken(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetToken(s)
	return rtuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableToken(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetToken(*s)
	}
	return rtuo
}

// SetIsClaimed sets the "is_claimed" field.
func (rtuo *RefreshTokenUpdateOne) SetIsClaimed(b bool) *RefreshTokenUpdateOne {
	rtuo.mutation.SetIsClaimed(b)
	return rtuo
}

// SetNillableIsClaimed sets the "is_claimed" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableIsClaimed(b *bool) *RefreshTokenUpdateOne {
	if b != nil {
		rtuo.SetIsClaimed(*b)
	}
	return rtuo
}

// SetUserID sets the "user_id" field.
func (rtuo *RefreshTokenUpdateOne) SetUserID(u uuid.UUID) *RefreshTokenUpdateOne {
	rtuo.mutation.SetUserID(u)
	return rtuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableUserID(u *uuid.UUID) *RefreshTokenUpdateOne {
	if u != nil {
		rtuo.SetUserID(*u)
	}
	return rtuo
}

// SetUpdatedAt sets the "updated_at" field.
func (rtuo *RefreshTokenUpdateOne) SetUpdatedAt(t time.Time) *RefreshTokenUpdateOne {
	rtuo.mutation.SetUpdatedAt(t)
	return rtuo
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (rtuo *RefreshTokenUpdateOne) SetUsersID(id uuid.UUID) *RefreshTokenUpdateOne {
	rtuo.mutation.SetUsersID(id)
	return rtuo
}

// SetUsers sets the "users" edge to the User entity.
func (rtuo *RefreshTokenUpdateOne) SetUsers(u *User) *RefreshTokenUpdateOne {
	return rtuo.SetUsersID(u.ID)
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtuo *RefreshTokenUpdateOne) Mutation() *RefreshTokenMutation {
	return rtuo.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (rtuo *RefreshTokenUpdateOne) ClearUsers() *RefreshTokenUpdateOne {
	rtuo.mutation.ClearUsers()
	return rtuo
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtuo *RefreshTokenUpdateOne) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdateOne {
	rtuo.mutation.Where(ps...)
	return rtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rtuo *RefreshTokenUpdateOne) Select(field string, fields ...string) *RefreshTokenUpdateOne {
	rtuo.fields = append([]string{field}, fields...)
	return rtuo
}

// Save executes the query and returns the updated RefreshToken entity.
func (rtuo *RefreshTokenUpdateOne) Save(ctx context.Context) (*RefreshToken, error) {
	rtuo.defaults()
	return withHooks(ctx, rtuo.sqlSave, rtuo.mutation, rtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) SaveX(ctx context.Context) *RefreshToken {
	node, err := rtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rtuo *RefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := rtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := rtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rtuo *RefreshTokenUpdateOne) defaults() {
	if _, ok := rtuo.mutation.UpdatedAt(); !ok {
		v := refreshtoken.UpdateDefaultUpdatedAt()
		rtuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtuo *RefreshTokenUpdateOne) check() error {
	if v, ok := rtuo.mutation.Token(); ok {
		if err := refreshtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.token": %w`, err)}
		}
	}
	if rtuo.mutation.UsersCleared() && len(rtuo.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RefreshToken.users"`)
	}
	return nil
}

func (rtuo *RefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *RefreshToken, err error) {
	if err := rtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	id, ok := rtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshtoken.FieldID)
		for _, f := range fields {
			if !refreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtuo.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.IsClaimed(); ok {
		_spec.SetField(refreshtoken.FieldIsClaimed, field.TypeBool, value)
	}
	if value, ok := rtuo.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if rtuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtoken.UsersTable,
			Columns: []string{refreshtoken.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtoken.UsersTable,
			Columns: []string{refreshtoken.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RefreshToken{config: rtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rtuo.mutation.done = true
	return _node, nil
}
