// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"automatic-doodle/ent"
	"automatic-doodle/modules/access-token/service"
	"automatic-doodle/modules/auth/middleware"
	rest2 "automatic-doodle/modules/auth/rest"
	service2 "automatic-doodle/modules/auth/service"
	factory3 "automatic-doodle/modules/file/factory"
	repository3 "automatic-doodle/modules/file/repository"
	rest4 "automatic-doodle/modules/file/rest"
	service4 "automatic-doodle/modules/file/service"
	factory4 "automatic-doodle/modules/job/factory"
	repository4 "automatic-doodle/modules/job/repository"
	rest5 "automatic-doodle/modules/job/rest"
	service5 "automatic-doodle/modules/job/service"
	factory5 "automatic-doodle/modules/jobAppl/factory"
	repository5 "automatic-doodle/modules/jobAppl/repository"
	rest6 "automatic-doodle/modules/jobAppl/rest"
	service6 "automatic-doodle/modules/jobAppl/service"
	rest3 "automatic-doodle/modules/profile/rest"
	"automatic-doodle/modules/refresh-token/factory"
	"automatic-doodle/modules/refresh-token/repository"
	"automatic-doodle/modules/router"
	factory2 "automatic-doodle/modules/user/factory"
	repository2 "automatic-doodle/modules/user/repository"
	"automatic-doodle/modules/user/rest"
	service3 "automatic-doodle/modules/user/service"
	"automatic-doodle/pkg/config"
	"automatic-doodle/pkg/encryption"
	"automatic-doodle/pkg/postgres"
	"automatic-doodle/pkg/s3_client"
	"automatic-doodle/pkg/server"
	"github.com/Wodemy-Labs/crawl"
)

// Injectors from wire.go:

func DBBuilder() *ent.Client {
	logger := _wireLoggerValue
	configLogger := _wireCrawlLoggerValue
	configModule := config.New(configLogger)
	client := postgres.New(logger, configModule)
	return client
}

var (
	_wireLoggerValue      = crawl.New("PostgresModule", nil)
	_wireCrawlLoggerValue = crawl.New("ConfigModule", nil)
)

func Wire(db *ent.Client) *server.Server {
	logger := _wireCrawlLoggerValue
	configModule := config.New(logger)
	serverLogger := _wireLoggerValue2
	middlewareLogger := _wireLoggerValue3
	serviceLogger := _wireLoggerValue4
	encryptionLogger := _wireLoggerValue5
	encryptionModule := encryption.New(configModule, encryptionLogger)
	logger2 := _wireLoggerValue6
	serviceService := service.New(configModule, logger2)
	repositoryRepository := repository.New(db)
	factoryFactory := factory.New(db, encryptionModule)
	userFactory := factory2.New(db, encryptionModule)
	userRepository := repository2.New(db)
	service7 := service2.New(serviceLogger, encryptionModule, serviceService, repositoryRepository, factoryFactory, userFactory, userRepository)
	middlewareMiddleware := middleware.New(middlewareLogger, service7)
	restRest := rest.New(middlewareMiddleware, userRepository)
	restLogger := _wireLoggerValue7
	rest7 := rest2.New(restLogger, service7, middlewareMiddleware)
	factory6 := factory3.New(db)
	repository6 := repository3.New(db)
	userService := service3.New(userRepository, userFactory, factory6, repository6)
	logger3 := _wireLoggerValue8
	rest8 := rest3.New(middlewareMiddleware, userService, logger3)
	logger4 := _wireLoggerValue9
	logger5 := _wireLoggerValue10
	s3clientLogger := _wireLoggerValue11
	s3clientService := s3client.New(s3clientLogger, configModule)
	service8 := service4.New(logger5, repository6, factory6, s3clientService)
	rest9 := rest4.New(logger4, service8, middlewareMiddleware)
	factory7 := factory4.New(db)
	repository7 := repository4.New(db)
	service9 := service5.New(repository7, userRepository)
	logger6 := _wireLoggerValue12
	rest10 := rest5.New(middlewareMiddleware, factory7, repository7, service9, logger6)
	factory8 := factory5.New(db)
	repository8 := repository5.New()
	service10 := service6.New(factory8, repository8, repository7, userRepository)
	logger7 := _wireLoggerValue13
	rest11 := rest6.New(service10, logger7, middlewareMiddleware)
	routerRouter := router.New(restRest, rest7, rest8, rest9, rest10, rest11)
	serverServer := server.New(configModule, serverLogger, routerRouter)
	return serverServer
}

var (
	_wireLoggerValue2  = crawl.New("ServerModule", nil)
	_wireLoggerValue3  = crawl.New("Authentication Middleware Logger", nil)
	_wireLoggerValue4  = crawl.New("AuthenticationService", nil)
	_wireLoggerValue5  = crawl.New("EncryptionModule", nil)
	_wireLoggerValue6  = crawl.New("AccessTokenService", nil)
	_wireLoggerValue7  = crawl.New("AuthRestLogger", nil)
	_wireLoggerValue8  = crawl.New("logger", nil)
	_wireLoggerValue9  = crawl.New("FileRest", nil)
	_wireLoggerValue10 = crawl.New("FileService", nil)
	_wireLoggerValue11 = crawl.New("S3Client", nil)
	_wireLoggerValue12 = crawl.New("JOB API LOGGER", nil)
	_wireLoggerValue13 = crawl.New("JobApplRest Module", nil)
)
